spring:
  datasource:
    url: jdbc:postgresql://3.38.42.240:5432/springboot
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: user
      password: 1111
      roles: USER

