spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: practice
    password: 12345
  jpa:
    hibernate:
      ddl-auto: validate
    #    properties:
    #      hibernate:
    #        format_sql: true
    #        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1

